### ISSUE TITLE
Formatted database for DADA2

### ISSUE THREAD

**Issue by tizioto** [marcomeola/DAIRYdb#1]
Dear all,

I would appreciate if you could format the database to use in DADA2/phyloseq pipeline please?

https://benjjneb.github.io/dada2/training.html

Thank you

All the Best,

Polyana

**Comment by marcomeola** [comment]
Hi Polyana,
we adapted the DAIRYdb to IDTAXA, which can be used in the DADA2 pipeline as described here https://benjjneb.github.io/dada2/tutorial.html. 
As we think that IDTAXA outperforms the assignTaxonomy function of DADA2, we did not adapt the database for that function. If you really want to stick to the assignTaxonomy function we can adapt it, but I would recommend to switch to IDTAXA.

**Comment by tizioto** [comment]
Dear Marco Meola, 
I am trying to use DAIRYdb to IDTAXA in  DADA2 pipeline as described here https://benjjneb.github.io/dada2/tutorial.html.
Please see my command: 
dna <- DNAStringSet(getSequences(seqtab.nochim)) 
load("~/DAIRYDB/DAIRYdb_v1.2.0_20190222_IDTAXA.RData") 
ids <- IdTaxa(dna, trainingSet, strand="top", processors=16, verbose=FALSE) 
ranks <- c("type", "domain", "phylum", "class", "order", "family", "genus", "species") 
taxid <- t(sapply(ids, function(x) {
        m <- match(ranks, x$rank)
        taxa <- x$taxon[m]
        taxa[startsWith(taxa, "unclassified_")] <- NA
        taxa
}))
colnames(taxid) <- ranks; rownames(taxid) <- getSequences(seqtab.nochim)

Please see how my ids object looks like:
> head(ids)
  A test set of class 'Taxa' with length 6
    confidence name                 taxon
[1]      72.4% ASV_1                Root; Bacteria; Firmicutes; Bacilli; Lact...
[2]      96.9% ASV_2                Root; Bacteria; Proteobacteria; Gammaprot...
[3]      94.2% ASV_3                Root; Bacteria; Firmicutes; Bacilli; Lact...
[4]      98.4% ASV_4                Root; Bacteria; Actinobacteria; Actinobac...
[5]      97.1% ASV_5                Root; Bacteria; Proteobacteria; Gammaprot...
[6]     100.0% ASV_6                Root; Bacteria; Proteobacteria; Gammaprot...

Howerver, taxid is all NA´s for all levels.
Do you have any recommendations?

Thank you 
Best Regards

**Comment by erifa1** [comment]
Dear Polyana,
The parsing step is not adapted to the idtaxa output. Ranks names are not informed in the reference. This can be improved in the next update of DAIRYdb. 

For the moment, I recommend you to use this script to assign your sequences: https://forgemia.inra.fr/umrf/utopia/blob/master/scripts/IDtaxa_assign.R

If you have a bash terminal, you just need to run this command: 
Rscript /pathto/IDtaxa_assign.R -r pathtoDB -s pathtoFASTA -o OUTPUTNAME

Otherwise, you can add to your script code lines 46->77.

Thanks for your feedback.
Etienne

**Comment by marcomeola** [comment]
Thank you Polyana for bringing up the issue and Etienne for adding the code here! That will be very helpful to integrate the tax. info into the dada2 pipeline.
That said, that issue is rather related to dada2 and should be corrected in the tutorial of dada2 or mentioned on the respective github page as well.

**Comment by tizioto** [comment]
Dear Etiene,

Thank you for your help. Your script worked fine.
However, I think the taxon table (dtff2) is in a format that is not
compatible with phyloseq.
Do you have a script ready to import it into phyloseq?

Dear Marco, I will post it on github DADA2.

Thank you

Best Regards,

Polyana

**Comment by erifa1** [comment]
Dear Polyana, 

I'm developping ANOMALY, a workflow which include DADA2 processing (16S or ITS) and downstream analysis (taxonomic assignment with IDTAXA, decontamination step, alpha/beta diversity analysis + statistical test associated, multiple differential analysis).

https://forgemia.inra.fr/umrf/anomaly/tree/master

There is a tutorial for more informations. You can leave feedback on the repository. 

Etienne
